### ISSUE TITLE
Python DiagnosedPublisher crashes on publishing headerless topic

### ISSUE THREAD

**Issue by JamesOwensMTC** [ros/diagnostics#308]
When publishing a headerless topic the node crashes with an AttributeError.

This is because:
1. The publish method of DiagnosedPublisher always attempts to use the timestamp from a header to 'tick' the TopicDiagnostic
1. The DiagnosedPublisher class in the python diagnostic_updater library initialises with a TopicDiagnostic task and never a HeaderlessTopicDiagnostic

The issue is within the following lines:

https://github.com/ros/diagnostics/blob/c8941bb72bef2309dee04a63c55f5b4437329632/diagnostic_updater/diagnostic_updater/_publisher.py#L116-L147

See below a redacted example of the traceback when publishing a String message:
```
Traceback (most recent call last):
  File "/home/username/catkin_ws/src/package/nodes/node.py", line 90, in <module>
    test_node.run()
  File  "/home/username/catkin_ws/src/package/nodes/node.py", line 219, in run
    self.monitored_pub.publish(m)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/diagnostic_updater/_publisher.py", line 143, in publish
    self.tick(message.header.stamp)
AttributeError: 'String' object has no attribute 'header'
[test_node-1] process has died [pid 17561, exit code 1, cmd /home/username/catkin_ws/src/package/nodes/node.py __name:=test_node __log:=/home/username/.ros/log/c92fbda4-158b-11ee-9322-080027d21e5a/test_node-1.log].
log file: /home/username/.ros/log/c92fbda4-158b-11ee-9322-080027d21e5a/test_node-1*.log
```

I experienced this issue using the library in ROS 1, but the same situation is evidently present in the ROS 2 code.

**Comment by ct2034** [comment]
@JamesOwensMTC Thanks for reporting this. What is your suggestion to fix this?

**Comment by JamesOwensMTC** [comment]
@ct2034 Following the pattern of the rest of this module a new class HeaderlessDiagnosedPublisher could be added.

This could look something like:
``` python
class HeaderlessDiagnosedPublisher(HeaderlessTopicDiagnostic):
    """
    A HeaderlessTopicDiagnostic combined with a ros::Publisher.

    For a standard ros::Publisher, this class allows the ros::Publisher and
    the HeaderlessTopicDiagnostic to be combined for added convenience.
    """

    def __init__(self, pub, diag, freq):
        """
        Construct a HeaderlessDiagnosedPublisher.

        @param pub The publisher on which statistics are being collected.
        @param diag The diagnostic_updater that the CompositeDiagnosticTask
        should add itself to.
        @param freq The parameters for the FrequencyStatus class that will be
        computing statistics.
        """
        HeaderlessTopicDiagnostic.__init__(self, pub.topic_name, diag, freq)
        self.publisher = pub

    def publish(self, message):
        """
        Collect statistics and publishes the message.
        """
        self.tick()
        self.publisher.publish(message)
```

**Comment by ct2034** [comment]
If you need a monitored publisher for messages without a header, I would suggest following an approach similar to src/diagnostics/diagnostic_updater/diagnostic_updater/example.py 
If you want to contribute something similar to your example, PRs are welcome.
